#Server Port
server.port=8081

#Application Name
spring.application.name=auth-service

#Postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartflow_auth
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


